### ISSUE TITLE
Integrate with AppVeyor

### ISSUE THREAD

**Issue by savornicesei** [ccnet/CruiseControl.NET#267]
Build CC.NET on AppVeyor (AV) on pull requests, commits.
Nightlies can be built after asking AV team for this feature.

**Comment by savornicesei** [comment]
Hi @RubenWillems 
Did you have time to setup AppVeyor integration for CruiseControl.NET project?

Thanks,
Simo

**Comment by RubenWillems** [comment]
Hi

Yes that has been done, and a build has already been forced.
I'm a bit busy for the moment (recently changed jobs) but I can make time
again for CCNet,
and surely now there are new people helping out.


with kind regards
Ruben Willems

**Comment by savornicesei** [comment]
Wow @RubenWillems - have fun at your new working place!

What's the link to the AppVeyor? I would like to add a build badge on the README page.

Best,
Simo

**Comment by RubenWillems** [comment]
Hi

could it be this one :
https://ci.appveyor.com/project/RubenWillems/cruisecontrol-net

or dit I something wrong in setting it up?

regards
Ruben Willems

**Comment by RubenWillems** [comment]
Hi

I got it to work at :
https://ci.appveyor.com/project/ccnet/cruisecontrol-net

that is better.

can you check that it is working?


with kind regards
Ruben Willems

**Comment by savornicesei** [comment]
Hi @RubenWillems 
Yes, the https://ci.appveyor.com/project/ccnet/cruisecontrol-net works. Nice!

I think it needs some more tinkering. Version should be 1.9.0-SNAPSHOT or some other text that would make it clear it's not an official release. 
GitVersion does not understand the existing tags and the latest release tag (1.8.5) is missing so we need some tweaks on this part until next release (with a proper tag).

It would also be nice to upload tests results in AppVeyor and display them in a badge on the README page.

Regarding code quality - we can use [SonarCloud](https://sonarcloud.io). It's free for OSS projects.

Let me know your thoughts on this

Best,
Simo

**Comment by RubenWillems** [comment]
Hi

that version stuff, I'll look into it.
About the 1.8 releases, those are in a seperate branch, not the master
branch.
Suppose we would release a 1.8.6, the code changes for that should go to :
release/CCNet-1.8

the master branch has code for 1.9. at least that was the plan years ago.

I'm looking at the sonarCloud, looks promising, but I have to see if I can
hook it up as the CCNet organisation.
and not under my own account. Because that would also grant access to
"  *Emails
(read)* View your email addresses  "
With appveyor, you could easily set it up as the organisation.

About the releases, maybe we should set up a separate thread on that.
° do we still want to release a 1.8.X?
° ....


let me know what you think.

with kind regards
Ruben Willems

**Comment by RubenWillems** [comment]
Hi

I got the sonarcloud to work as organization, but I need to download and
install an exe.
Supposedly that should go in the tools folder and into the build script I
think.

Is that correct ? I never worked with sonarcloud before.


with kind regards
Ruben Willems

**Comment by savornicesei** [comment]
No. That will be handled by cake on the build machine (appveyor) at build time. 
I'll create a separate ticket for the Sonarcloud (SQ) on which I'll do the required changes.

Regarding versioning and releases - yeah, we should discuss it on a separate thread.

Best,
Simo

**Comment by RubenWillems** [comment]
initial setup has been done. If it needs updating, this can be done via the build scripts. If needs be, a new issue item may be created of course.
